using LUP.ES;
using Roguelike.Define;
using System;
using System.Collections.Generic;
using UnityEngine;
namespace LUP.RL
{
    public class Archer : MonoBehaviour
    {
        [Header("ДіёҜЕН ЕЫЗГёҙ өҘАМЕН (SO)")]
        [SerializeField] private RLCharacterData characterTemplate;


        [Header("·ұЕёАУ өҘАМЕН")]
        private RunTimeData runtimeData; 


        [SerializeField] public LevelDataTable levelTable;
        //public BaseStats stats;

        //[Header("№цЗБ °ь·Г")]
        //public List<BuffData> allBuffs;          // АОҪәЖеЕНҝЎјӯ өо·П
        //public GameObject buffSelectionUI;       // АьГј ЖРіО (Canvas ҫИ)
        //public Transform optionParent;           // №цЖ°өйА» іЦА» әОёр (ҝ№: Horizontal Layout)
        //public GameObject optionButtonPrefab;    // №цЖ° ЗБё®ЖХ (Textёё АЦҫоөө OK)

        public event System.Action OnExpChanged;
        public event System.Action OnArcherDataReady;
        List<BuffData> randomBuffs = new List<BuffData>();
        List<BuffData> GetBuffList = new List<BuffData>();

        [Header("UI ")]
        [SerializeField]
        private Hpbar hpbar;
        public GameObject HpbarPrefab;
        private HealthCenter healthCenter;
        [SerializeField] private float hpbaroffsetY = 5;
        // ҝЬәО БўұЩҝл ЗБ·ОЖЫЖј
        public RunTimeData RuntimeData => runtimeData;
        public HealthCenter HealthCenter => healthCenter;

        private PlayerBuff playerBuff;
        public PlayerBuff PlayerBuff => playerBuff;
        void Awake()
        {
           
            InitializeCharacter();
            healthCenter = new HealthCenter(RuntimeData.currentData.MaxHp);

        }
        private void Start()
        {
            InitaliUI();
            playerBuff = GetComponent<PlayerBuff>();
            playerBuff.init(this);
            playerBuff.ShowBuffSelection();
        }
        private void InitializeCharacter()
        {
            if(characterTemplate == null)
            {
                Debug.Log("null template data");
            }
            runtimeData = new RunTimeData(characterTemplate);
            OnArcherDataReady?.Invoke();
            Debug.Log($"[Archer] ДіёҜЕН ГКұвИӯ ҝП·б - Гј·В: {runtimeData.currentData.MaxHp}, °ш°Э·В: {runtimeData.currentData.Attack}");
        }
        private void InitaliUI()
        {
            GameObject barObj = Instantiate(HpbarPrefab, transform.position + Vector3.up * hpbaroffsetY, Quaternion.identity);
            hpbar = barObj.GetComponent<Hpbar>();
            hpbar.Init(this);
        }

     
        public void ApplyBuff(BuffData buff)
        {
            if (buff == null) Debug.Log("null");
            switch (buff.type)
            {
                case BuffType.AddMaxHp:
                    RuntimeData.currentData.Attack += 5;
                    break;

                case BuffType.AddAtkHigh:
                    RuntimeData.currentData.Hp += 30;
                    break;

                case BuffType.AddSpeed:
                    RuntimeData.currentData.speed += 1;
                    break;
            }
            GetBuffList.Add(buff);
        }
        private void OnEnable()
        {
         
            Enemy.OnEnemyDied += GainExp;
            if(healthCenter != null)
            {
                healthCenter.OnDead += Die;
            }
         

        }
        public void TakeDamage(int damage)
        {
            healthCenter.Damage(damage);

        }
        private void Die()
        {
            Destroy(gameObject, 0.1f);
        }
        private void OnDisable()
        {
            Enemy.OnEnemyDied -= GainExp;
        }
        private void GainExp(int exp)
        {
            var data = levelTable.GetLevelData(RuntimeData.level);
            RuntimeData.xp += exp;
            if (RuntimeData.xp >= data.RequiredExp)
                LevelUp();
            OnExpChanged?.Invoke();
        }
        private void LevelUp()
        {
            RuntimeData.level++;
            RuntimeData.xp = 0;
            var levelData = levelTable.GetLevelData(RuntimeData.level);
            if (levelData != null)
            {
                RuntimeData.currentData.Attack = levelData.AttackBouns;
                RuntimeData.currentData.Hp = levelData.HpBouns;
                RuntimeData.currentData.MaxHp = levelData.HpBouns;
            }
            playerBuff.ShowBuffSelection();
            Debug.Log($"·№ә§{RuntimeData.level}, Гј·В :  {RuntimeData.currentData.Hp} ,  °ш°Э·В  {RuntimeData.currentData.Attack}");
        }
        
    }
}