using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.Experimental.GraphView;
using UnityEngine;

namespace LUP.RL
{

    public enum ActionState
    {
        MoveTo,
        Attack,
        Hitted,
        Wait,
        Die
    }

    public class BaseBehaviorTree : MonoBehaviour
    {
        protected Animator Animator;
        protected AnimatorStateInfo stateInfo;

        protected RootNode rootnode;
        protected EnemyBlackBoard enemyBlackBoard;
        protected CompositeNode topCompositeNode;

        private LeafNode currentRunningLeaf;

        private void Awake()
        {
            enemyBlackBoard = GetComponent<EnemyBlackBoard>();
            Animator = GetComponent<Animator>();

            enemyBlackBoard.HP = enemyBlackBoard.MaxHP;
        }
        // Start is called once before the first execution of Update after the MonoBehaviour is created
        void Start()
        {
            if (Animator != null)
            {
                AnimatorCallBack[] animatorCallBacks = Animator.GetBehaviours<AnimatorCallBack>();
                for (int i = 0; i < animatorCallBacks.Length; i++)
                {
                    animatorCallBacks[i].SetAnimEndCallBack(OnAnimationEnd);
                }

                //StateMachineBehaviourИІ ОжДЯИоРЬМЧ ЛѓХТ(State) ДмРЇЗЮ ЁАКЙСІЁБЧиМ­ АќИЎЧи.
                //Ся, Attack, Hitted, Idle АЂАЂРЬ РќКЮ РкБт РќПыРЧ AnimatorCallBack РЮНКХЯНКИІ АЎАэ РжДТ АХОп.
                //ЧЯГЊИИ УЃОЦМ­ АЁСЎПРИщ, УЙЙјТА Г№ ИИ ЕюЗЯРЬ ЕЧОю СјДй.
                //Animator.GetBehaviour<AnimatorCallBack>().SetAnimEndCallBack(OnAnimationEnd);
            }

            InitBehaviorTree();
        }

        public virtual void InitBehaviorTree()
        {

        }

        // Update is called once per frame
        void Update()
        {
            if (enemyBlackBoard.Alive == false)
                return;

            if (rootnode != null)
            {
                rootnode.Evaluate();
            }

        }

        public void PlayAnimation(ActionState actionState, LeafNode caller)
        {
            if (Animator == null)
                return;

            string calledAnimName = "None";

            switch (actionState)
            {
                case ActionState.MoveTo:
                    calledAnimName = "MoveTo";
                    break;

                case ActionState.Attack:
                    calledAnimName = "Attack";
                    break;

                case ActionState.Hitted:
                    calledAnimName = "Hitted";
                    break;

                case ActionState.Wait:
                    calledAnimName = "Wait";
                    break;

                case ActionState.Die:
                    calledAnimName = "Die";
                    break;

                default:
                    break;
            }

            stateInfo = GetCurrentAnimState();

            if (stateInfo.IsName("Wait") || stateInfo.IsName("MoveTo"))
            {
                currentRunningLeaf = caller;
                Animator.Play(calledAnimName);
            }

            
        }

        public void OnAnimationEnd(AnimatorStateInfo info)
        {
            if (currentRunningLeaf == null)
                return;

            currentRunningLeaf.OnAnimationEnd(info);
            currentRunningLeaf = null;
        }

        public AnimatorStateInfo GetCurrentAnimState()
        {
            stateInfo = Animator.GetCurrentAnimatorStateInfo(0);
            return stateInfo;
        }
    }
}



