using System.Collections.Generic;
using UnityEngine;

public class MovingPlatform : MonoBehaviour
{
    [Header("МГСЄ")]
    public List<Transform> points = new List<Transform>();
    public float moveTime = 2f;

    private bool isMoving = false;
    private int currentIndex = 0;
    private int nextIndex = 1;
    private float currentTime = 0f;

    void Start()
    {
        if (points.Count < 2)
        {
            Debug.LogError("ЦїРЮЦЎАЁ 2АГ РЬЛѓ ЧЪПфЧеДЯДй.");
            enabled = false;
            return;
        }

        transform.position = points[0].position;
    }

    void Update()
    {
        if (!isMoving) return;

        currentTime += Time.deltaTime;
        float t = currentTime / moveTime;

        Vector3 startPos = points[currentIndex].position;
        Vector3 endPos = points[nextIndex].position;

        transform.position = Vector3.Lerp(startPos, endPos, t);

        if (t >= 1f)
            Arrive();
    }

    public void StartMove()
    {
        if (!isMoving)
        {
            isMoving = true;
            currentTime = 0f;
            Debug.Log($"ПЄИЎКЃРЬХЭ РЬЕП НУРл! {currentIndex} Ёц {nextIndex}");
        }
    }

    private void Arrive()
    {
        isMoving = false;
        Debug.Log("ПЄИЎКЃРЬХЭ ЕЕТј!");

        currentIndex = nextIndex;
        nextIndex = (nextIndex + 1) % points.Count;
    }
    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Player"))
        {
            other.transform.SetParent(this.transform);
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.CompareTag("Player"))
        { 
            other.transform.SetParent(null, true);
        }
    }
}