using System;
using System.Collections.Generic;
using UnityEngine;

namespace LUP.PCR
{
    [RequireComponent(typeof(Worker))]
    [RequireComponent(typeof(UnitMover))]
    public class WorkerAI : MonoBehaviour
    {
        [Header("State")]
        [SerializeField] private float hunger;
        [SerializeField] private BuildingBase dest; 
        private bool Ishunger;
        private bool hasNewTask = false;
        private bool hasPausedTask = false;

        [Header("BT Time")]
        private float btTickInterval = 0.1f;
        private float btTimer = 0f;

        [Header("Component")]
        private Worker worker;
        private UnitMover mover;
        private IUnitMoveable moverAdapter;
        private BTNode root;

        // ЗЮФУ КэЗЂКИЕх->ЕПРћ ЕЅРЬХЭ ЕПБтШ­
        // WorkerAIРЧ КЏМі АЊРЬ ЙйВюИщ -> КэЗЂКИЕхЕЕ СяНУ ОїЕЅРЬЦЎЕЪ
        // BT ГыЕхЕщРК КЏМіИІ СїСЂ ОШ КИАэ КэЗЂКИЕхРЧ KeyИИ КН
        public void InitBTRules()
        {
            Ishunger = hunger >= HungerRules.Hunger;
        }

        public WorkerBlackboard LocalBlackboard { get; private set; }
        public float Hunger
        {
            get => hunger;
            set
            {
                hunger = value;
                LocalBlackboard.SetValue(BBKeys.Hunger, hunger);
            }
        }

        public bool HasNewTask
        {
            get => hasNewTask;
            set
            {
                hasNewTask = value;
                LocalBlackboard.SetValue(BBKeys.HasNewTask, hasNewTask);
            }
        }
        public bool HasPausedTask
        {
            get => hasPausedTask;
            set
            {
                hasPausedTask = value;
                LocalBlackboard.SetValue(BBKeys.HasPausedTask, hasPausedTask);
            }
        }

        // Л§Лъ РлОї ТќСЖ
        private ProductableBuilding currentTaskBuilding = null;
        private ProductableBuilding pausedTaskBuilding = null;
        private ProductableBuilding newAssignedBuilding = null;

        private void Awake()
        {
            worker = GetComponent<Worker>();
            mover = GetComponent<UnitMover>();
            moverAdapter = mover as IUnitMoveable;

            LocalBlackboard = new WorkerBlackboard();
            InitBlackboard();
        }
        private void InitBlackboard()
        {
            //СЄРћ ЕЅРЬХЭ(ТќСЖ) ЕюЗЯ
            LocalBlackboard.SetValue(BBKeys.OwnerAI, this);
            LocalBlackboard.SetValue(BBKeys.Self, worker);
            LocalBlackboard.SetValue(BBKeys.UnitMover, moverAdapter);

            // BT ЛѓХТ УЪБтШ­
            LocalBlackboard.SetValue(BBKeys.Hunger, hunger);
            bool IsHunger = hunger >= HungerRules.Hunger;
            LocalBlackboard.SetValue(BBKeys.IsHungry, IsHunger);

            LocalBlackboard.SetValue<BuildingBase>(BBKeys.TargetBuilding, dest);
            LocalBlackboard.SetValue<Vector2Int>(BBKeys.TargetPosition, dest.entrancePos);

            LocalBlackboard.SetValue(BBKeys.HasNewTask, hasNewTask);
            LocalBlackboard.SetValue(BBKeys.HasNewTask, hasNewTask);


            LocalBlackboard.SetValue(BBKeys.HasNewTask, hasNewTask);
            LocalBlackboard.SetValue(BBKeys.HasPausedTask, hasPausedTask);
        }

        private void Start()
        {
            SettingBT();
        }

        void SettingBT()
        {
            // И№Еч Leaf Node Л§МКРкПЁ LocalBlackboardИІ РќДо (СжРд)
            // CompositeNode(Sequence/Selector)ДТ КэЗЂКИЕхАЁ ЧЪПф ОјРИЙЧЗЮ ИЎНКЦЎИИ РќДо

            // Sequence: ЙшАэЧФ УГИЎ
            BTNode hungerSequence = new SequenceNode(new List<BTNode>
         {
             new IsHealthLowChecker(LocalBlackboard),
             new PauseCurrentTask(LocalBlackboard),
             new GoToEatingPlace(LocalBlackboard),
             new ReturnToPausedTask(LocalBlackboard),
             new EatFood(LocalBlackboard),
         });

            // Sequence: ЧЯДј РЯ РчАГ
        BTNode resumeTaskSequence = new SequenceNode(new List<BTNode>
        {
            new IsPausedTaskChecker(LocalBlackboard),
            new GoToPausedTaskLocation(LocalBlackboard),
            //new ResumePausedTask(LocalBlackboard)
        });

            // Sequence: Лѕ РЯ НУРл
        BTNode newTaskSequence = new SequenceNode(new List<BTNode>
        {
            new IsNewTaskChecker(LocalBlackboard),
            new GoToNewTaskLocation(LocalBlackboard),
            //new StartNewTask(LocalBlackboard)
        });

            // Selector: РлОї/ШоНФ
        BTNode taskSelector = new SelectorNode(new List<BTNode>
        {
            resumeTaskSequence,
            newTaskSequence,
            new GoToLounge(LocalBlackboard)
        });

            // Root Selector: ЙшАэЧФ Ёц РлОї/ШоНФ
            root = new SelectorNode(new List<BTNode>
            {
                hungerSequence,
                taskSelector
            });

        }
        

        private void Update()
        {
            if (root == null) return;
            root?.Evaluate();
            // Hunger = Mathf.Clamp01(hunger - Time.deltaTime * 0.01f);

            // protected, private КИШЃМіСиПЁ ИЗШћ.
            // @TODO: ProductableBuildingРЧ currBuildState АЁСЎПРДТ ЙцЙ§ АэЙЮЧЯБт 
            //if (currentTaskBuilding != null && currentTaskBuilding.currBuildState is ProductableState pState && pState != null)
            //{
            //    // @TODO: ProductableState dataИІ КэЗЂКИЕхПЁ ЕюЗЯЧв Мі РжДТ ЧдМі ЧЪПф.
            //    // КэЗЂКИЕх Л§Лъ ЕЅРЬХЭ ОїЕЅРЬЦЎ
            //    LocalBlackboard.SetValue(BBKeys.ProductionStateData, pState.data);
            //    LocalBlackboard.SetValue(BBKeys.IsProductionCompleted, pState.data.IsCompleted);
            //    LocalBlackboard.SetValue(BBKeys.ProductionProgress, pState.data.Progress);

            //btTimer += Time.deltaTime;
            //if (btTimer >= btTickInterval)
            //{
            //    btTimer = 0f;
            //}
            //}
        }
        public void AssignTask(ProductableBuilding building)
        {
            CancelOrReplaceCurrentTask();

            newAssignedBuilding = building;
            HasNewTask = true;

            LocalBlackboard.SetValue(BBKeys.TargetBuilding, building);

            //@TODO : БИСЖ ШЎСЄЕЧИщ УпАЁЧЯБт
            //LocalBlackboard.SetValue(BBKeys.TargetPosition, building.GetWorkerEntranceWorldPos(null));
            //if (building.currBuildState is ProductableState ps)
            {
                //LocalBlackboard.SetValue(BBKeys.ProductionStateData, ps.Data);
                //LocalBlackboard.SetValue(BBKeys.IsProductionCompleted, ps.Data.IsCompleted);
                //LocalBlackboard.SetValue(BBKeys.ProductionProgress, ps.Data.Progress);
            }
        }

        private void CancelOrReplaceCurrentTask()
        {
            if (currentTaskBuilding != null)
            {
                // store as paused task only if we will resume it later (hunger case)
                pausedTaskBuilding = currentTaskBuilding;
                HasPausedTask = true;
            }
            currentTaskBuilding = null;
            LocalBlackboard.Remove(BBKeys.TargetBuilding);
            LocalBlackboard.Remove(BBKeys.TargetPosition);
            HasNewTask = false;
        }

        public void ClearPausedTask()
        {
            pausedTaskBuilding = null;
            HasPausedTask = false;
        }

        public void StartWorkingAt(ProductableBuilding building)
        {
            LocalBlackboard.SetValue(BBKeys.TargetBuilding, building);
            //LocalBlackboard.SetValue(BBKeys.TargetPosition, building.GetWorkerEntranceWorldPos(null));
            //OnTaskStarted?.Invoke(this);
        }
        public void FinishWorking()
        {
            currentTaskBuilding = null;
           // OnTaskFinished?.Invoke(this);
        }

        public void OnAte()
        {
            Hunger = 0f;
           // OnEatCompleted?.Invoke(this);
        }

    }

}