using System.Collections.Generic;
using System.Text;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

namespace LUP.ES
{
    public class ResultDisplayCenter : MonoBehaviour
    {
        private EventBroker eventBroker;
        private ItemCenter itemCenter; //ลืฝบฦฎ ฟ๋
        public GameObject resultPanel;
        public GameObject ItemDisplayContent;
        public GameObject itemSlotPrefab;
        public Text resultHeader;
        //public Button lobbyButton;

        private Transform contentParent;
        private List<Item> items;
        private void Start()
        {
            resultPanel.SetActive(false);
            //lobbyButton.onClick.AddListener(LoadLobby);
            eventBroker = FindAnyObjectByType<EventBroker>();
            itemCenter = FindAnyObjectByType<ItemCenter>();
            contentParent = ItemDisplayContent.transform;
            if (eventBroker != null )
            {
                eventBroker.OnGameFinished += ShowResult;
            }
        }

        private void OnDestroy()
        {
            if (eventBroker != null)
            {
                eventBroker.OnGameFinished -= ShowResult;
            }
        }

        public void ShowInventoryItems(List<Item> items)
        {
            for (int i = 0; i < items.Count; i++)
            {
                GameObject newSlot = Instantiate(itemSlotPrefab, contentParent);

                ItemDisplaySlot slot = newSlot.GetComponent<ItemDisplaySlot>();
                if (slot != null)
                {
                    slot.SetItem(items[i]);
                }
            }
        }

        private void ShowResult(bool isSuccess)
        {
            Debug.Log("GameFinish");
            Time.timeScale = 0f;
            StringBuilder resultHeadrString = new StringBuilder();
            resultHeadrString.Append("ลปรโ ");
            resultPanel.SetActive(true);
            if (isSuccess)
            {
                resultHeadrString.Append("ผบฐ๘");
                items = itemCenter.GenerateLoot();
                ShowInventoryItems(items);
            }
            else
                resultHeadrString.Append("ฝวฦะ");
            resultHeader.text = resultHeadrString.ToString();
        }
    }
}
