using LUP.ES;
using System.Collections.Generic;
using TMPro;
using UnityEngine;

namespace LUP.ES
{
    public class Door : MonoBehaviour, IInteractable
    {
        [Header("МГСЄ")]
        [SerializeField] private float OpenDoorTime = 1.5f;

        [Header("ТќСЖ")]
        public EventBroker eventBroker;
        private InteractionUIController interactionUI;

        public bool isOpening;
        public bool IsOpening() { return isOpening; }

        public bool isOpened = false;
        private float currentTime = 0.0f;
        public bool InterruptsOnMove => true;
        public bool CanInteract() => !isOpening && !isOpened;
        // Start is called once before the first execution of Update after the MonoBehaviour is created
        void Start()
        {
            interactionUI = GetComponent<InteractionUIController>();
            HideInteractionPrompt();
        }

        // Update is called once per frame
        void Update()
        {

        }
        public void Interact()
        {
            HideInteractionPrompt();
            HideInteractionTimerUI();

            Debug.Log("ЙЎ П­ИВ!!!");
            isOpened = true;

            // 0.1УЪ Ек ЛшСІ (UI/ЛѓШЃРлПы НУНКХл ОїЕЅРЬЦЎ НУАЃ ШЎКИ)
            this.gameObject.SetActive(false);
        }

        public bool TryStartInteraction(float deltaTime)
        {
            if (!isOpening)
            {
                isOpening = true;
                currentTime = OpenDoorTime;

                ShowInteractionTimerUI();
                HideInteractionPrompt();

                return false;
            }

            currentTime -= deltaTime;

            interactionUI.UpdateInteractionTimerUI(OpenDoorTime, currentTime);
            if (currentTime < 0.0f)
            {
                Interact();
                return true;
            }
            return false;
        }

        public void ResetInteraction()
        {
            isOpening = false;
            currentTime = 0.0f;
        }

        public void ShowInteractionPrompt()
        {
            if(!isOpened)
            {
                interactionUI.ShowInteractionPrompt();
            } 
        }
        public void HideInteractionPrompt()
        {
            interactionUI.HideInteractionPrompt();
        }

        public  void ShowInteractionTimerUI()
        {
            interactionUI.ShowInteractionTimerUI();
        }

        public void HideInteractionTimerUI()
        {
            interactionUI.HideInteractionTimerUI();
        }
    }
}
